function updateReport
% UPDATEREPORT - This function builds the data reporting string which will
% eventually get sent to slack

    load("C://IREC-2026-Systems/Design Reporting/reportData1.mat");
    load("C://IREC-2026-Systems/Design Reporting/reportData2.mat");
    load("C://IREC-2026-Systems/Design Reporting/reportData3.mat");
    L = reportData3.length;
    D = reportData3.diameter;
    
    c1 = 3.28084; % m to ft
    c2 = 39.37008; % m to in
    c3 = L/(100*D); % percent to cal

    alt = reportData1.apogee;
    altInd = reportData1.apogee_indicated;
    target = reportData1.target;
    range = reportData1.range;
    t_low = target - 0.5*range;
    t_high = target + 0.5*range;
    error = reportData1.error;
    errPercent = 100*error/range;
    unc = reportData1.uncertainty;
    ctrl = reportData1.control;
    str1 = "1---APOGEE STATS" + newline...
        + "Apogee" + newline...
        + sprintf("     Status ------------------: %s", reportData1.status) + newline...
        + sprintf("     Geometric apogee [m, ft] : %.1f, %.0f", alt, alt*c1) + newline...
        + "     Target [m, ft] " + newline...
        + sprintf("          Center -------------: %.1f, %.0f", target, target*c1) + newline...
        + sprintf("          Range --------------: %.1f, %.0f", range, range*c1) + newline...
        + sprintf("          Lower bound --------: %.1f, %.0f", t_low, t_low*c1) + newline...
        + sprintf("          Upper bound --------: %.1f, %.0f", t_high, t_high*c1) + newline...
        + sprintf("     Apogee error [m, ft, %%%%] -: %.1f, %.0f, %.0f%%%%", error, error*c1, errPercent) + newline...
        + sprintf("     Indicated apogee [m, ft] : %.1f, %.0f", altInd, altInd*c1) + newline...
        + sprintf("     Uncertainty [m, ft] -----: %.1f, %.0f", unc, unc*c1) + newline...
        + sprintf("     Control authority [m, ft]: %.1f, %.0f", ctrl, ctrl*c1);
    
    accel = reportData2.maxAccel;
    Gs = accel/9.81;
    rodStab = reportData2.rodStab;
    maxStab = reportData2.maxStab;
    str2 = "2---PERFORMANCE" + newline...
        + "Motion" + newline...
        + sprintf("     Maximum speed [m/s] -----: %.1f", reportData2.maxSpeed) + newline...
        + sprintf("     Rod exit speed [m/s] ----: %.1f", reportData2.rodSpeed) + newline...
        + sprintf("     Max. accel. [m/s^2, g] --: %.1f, %.1f", accel, Gs) + newline...
        + sprintf("     Flight time [s] ---------: %.0f", reportData2.flightTime) + newline...
        + "Recovery" + newline...
        + sprintf("     Drogue descent rate [m/s]: %.2f", reportData2.drogueRate) + newline...
        + sprintf("     Drogue time [s] ---------: %.0f", reportData2.drogueTime) + newline...
        + sprintf("     Main descent rate [m/s] -: %.2f", reportData2.mainRate) + newline...
        + sprintf("     Main time [s] -----------: %.0f", reportData2.mainTime) + newline...
        + sprintf("     Ground hit speed [m/s] --: %.2f", reportData2.groundHit) + newline...
        + sprintf("     Max. snatch force [N] ---: %.0f", reportData2.snatch) + newline...
        + "Stability" + newline...
        + sprintf("     Rod exit [%%%%, cal] -------: %.2f%%%%, %.2f", rodStab, rodStab*c3) + newline...
        + sprintf("     Burnout [%%%%, cal] --------: %.2f%%%%, %.2f", maxStab, maxStab*c3) + newline...
        + "Flutter" + newline...
        + sprintf("     Flutter speed [m/s] -----: %.1f", reportData2.flutterSpeed) + newline...
        + sprintf("     Flutter margin ----------: %.2f", reportData2.flutterMargin) + newline...
        + "Other" + newline...
        + sprintf("     Max q [kPa] -------------: %.2f", reportData2.q/1000) + newline...
        + sprintf("     Speed at max q [m/s] ----: %.1f", reportData2.qVel) + newline...
        + sprintf("     time at max q [s] -------: %.2f", reportData2.qTime);

    mainC = [reportData3.mainCharges(1), reportData3.mainCharges(2)];
    drogueC = [reportData3.drogueCharges(1), reportData3.drogueCharges(2)];
    str3 = "3---DESIGN" + newline...
        + "Dimensions" + newline...
        + sprintf("     Length [in] -------------: %.0f", reportData3.length*c2) + newline...
        + sprintf("     Diameter [in] -----------: %.2f", reportData3.diameter*c2) + newline...
        + sprintf("     Reference area [m^2] ----: %.4f", reportData3.area) + newline...
        + "Rocket Mass [kg]" + newline...
        + sprintf("     Fully loaded ------------: %.2f", reportData3.massLoaded) + newline...
        + sprintf("     No motor ----------------: %.2f", reportData3.massNoMotor) + newline...
        + sprintf("     Burnout -----------------: %.2f", reportData3.massBurnout) + newline...
        + sprintf("     Empty -------------------: %.2f", reportData3.massEmpty) + newline...
        + sprintf("     Target ------------------: %.2f", reportData3.massTarget) + newline...
        + sprintf("     Error -------------------: %.2f", reportData3.massErr) + newline...
        + "System Masses [kg]" + newline...
        + sprintf("     Airbrakes ---------------: %.3f", reportData3.ABMass) + newline...
        + sprintf("     Avionics ----------------: %.3f", reportData3.avMass) + newline...
        + sprintf("     Payload -----------------: %.3f", reportData3.payloadMass) + newline...
        + "Recovery" + newline...
        + "     Main" + newline...
        + sprintf("          Diameter [in] ------: %.0f", reportData3.mainDiameter*c2) + newline...
        + sprintf("          Area [m^2] ---------: %.4f", reportData3.mainArea) + newline...
        + sprintf("          Cd -----------------: %.2f", reportData3.mainCD) + newline...
        + sprintf("          Charge sizes [g] ---: %.2f, %.2f", mainC(1), mainC(2)) + newline...
        + sprintf("          4-40 pins ----------: %.0f", reportData3.mainPins) + newline...
        + "     Drogue" + newline...
        + sprintf("          Diameter [in] ------: %.0f", reportData3.drogueDiameter*c2) + newline...
        + sprintf("          Area [m^2] ---------: %.4f", reportData3.drogueArea) + newline...
        + sprintf("          Cd -----------------: %.2f", reportData3.drogueCD) + newline...
        + sprintf("          Charge sizes [g] ---: %.2f, %.2f", drogueC(1), drogueC(2)) + newline...
        + sprintf("          4-40 pins ----------: %.0f", reportData3.droguePins);
    
    % Write the report
    outStr = str1 + newline + newline + str2 + newline + newline + str3;
    f_ID = fopen("C://IREC-2026-Systems/Design Reporting/Report.txt", "w");
    fprintf(f_ID, outStr);
    fclose(f_ID);

    % Silly emoji
    if reportData1.status == "UNDERSHOOT" || reportData1.status == "OVERSHOOT"
        emojiStr = ":wa:";
    else
        emojiStr = ":him2:";
    end
    f_ID = fopen("C://IREC-2026-Systems/Design Reporting/emoji.txt", "w");
    fprintf(f_ID, emojiStr);
    fclose(f_ID);
end

